// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFmfqXI164WNox7UbZEaQneCPlzwgVqLY',
    appId: '1:661068381268:web:64fcea7411a480c012c1c1',
    messagingSenderId: '661068381268',
    projectId: 'past-question-achieve',
    authDomain: 'past-question-achieve.firebaseapp.com',
    storageBucket: 'past-question-achieve.firebasestorage.app',
    measurementId: 'G-J9ZV1199B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgSHkk74B-l0-H2H2HsQW3kW0QCuJ6ogM',
    appId: '1:661068381268:android:cb41d8c8251e536c12c1c1',
    messagingSenderId: '661068381268',
    projectId: 'past-question-achieve',
    storageBucket: 'past-question-achieve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8aZ7_ZLFyUeeP70QqkSq7C72u4O83mbc',
    appId: '1:661068381268:ios:9c50179446e92c6f12c1c1',
    messagingSenderId: '661068381268',
    projectId: 'past-question-achieve',
    storageBucket: 'past-question-achieve.firebasestorage.app',
    iosBundleId: 'com.example.pastQuestions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8aZ7_ZLFyUeeP70QqkSq7C72u4O83mbc',
    appId: '1:661068381268:ios:9c50179446e92c6f12c1c1',
    messagingSenderId: '661068381268',
    projectId: 'past-question-achieve',
    storageBucket: 'past-question-achieve.firebasestorage.app',
    iosBundleId: 'com.example.pastQuestions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFmfqXI164WNox7UbZEaQneCPlzwgVqLY',
    appId: '1:661068381268:web:ce550607ec938c6b12c1c1',
    messagingSenderId: '661068381268',
    projectId: 'past-question-achieve',
    authDomain: 'past-question-achieve.firebaseapp.com',
    storageBucket: 'past-question-achieve.firebasestorage.app',
    measurementId: 'G-V64QD1XK6H',
  );

}